version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=kephrr_tp2
      - DB_USER=kephrr
      - DB_PASS=YTRADIUS0

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=kephrr_tp2
      - MYSQL_USER=kephrr
      - MYSQL_PASSWORD=YTRADIUS0
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
